### PR TITLE
Add feature navigate between channels in Player

### PR DESCRIPTION
**Pull request by tungnk123**

### CODE REVIEW

**Review by oxyroid — CHANGES_REQUESTED** [review]
Please revert some unnecessary formatting changes. Including Linebreak and contraction.

**Review by oxyroid — CHANGES_REQUESTED** [review]

**Comment by oxyroid** [comment]
I have a new idea to find out the adjacent channels:
#### Define a new class to hold the SQL result.
```kotlin
// Channel.kt
data class AdjacentChannels(
    @ColumnInfo("prev")
    val prev: Channel?,
    @ColumnInfo("next")
    val next: Channel?
)
```
#### Add a method which returns "Flow"
```kotlin
// ChannelDao.kt
/**
 * Observe the two channels adjacent to a specific channel in a particular channel order.
 * If the channel is not in this channel order, a null object will be returned.
 */
@Query(
    """
        Write SQL here.
    """
)
fun observeAdjacentChannels(
    channelId: Int,
    playlistUrl: String,
    category: String
): Flow<AdjacentChannels?>
```
- You can refer to the observeProgrammeRange method in ProgrammeDao. It shows you how to map a custom object to a SQL statement.
- You can refer to the pagingAllByPlaylistUrl method in ChannelDao. It shows you how the channel order should be.

**Comment by oxyroid** [comment]
You can try this SQL statement:
```sql
-- ChatGPT
WITH Ranked AS (
    SELECT *, ROW_NUMBER() OVER (ORDER BY name) AS rn
    FROM channels
)
SELECT * FROM Ranked
WHERE rn BETWEEN (
    SELECT rn FROM Ranked WHERE id = :channelId AND category = :category AND playlist_url = :playlistUrl
) - 1 AND (
    SELECT rn FROM Ranked WHERE id = :channelId AND category = :category AND playlist_url = :playlistUrl
) + 1;
```

**Comment by tungnk123** [comment]
Could you pls review this pull request?

**Pull request closed without merging**
